import React, { useState, useEffect } from 'react';
import { X, DollarSign, TrendingUp, Info, Loader2, RefreshCw } from 'lucide-react';
import { JobOpportunity, CVAnalysis } from '../types';
import { estimateSalary } from '../services/geminiService';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  job: JobOpportunity;
  analysis: CVAnalysis;
}

interface SalaryData {
  min: number;
  max: number;
  currency: string;
  confidence: string;
  explanation: string;
}

const SalaryModal: React.FC<Props> = ({ isOpen, onClose, job, analysis }) => {
  const [data, setData] = useState<SalaryData | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (isOpen && job) {
      fetchEstimate();
    }
  }, [isOpen, job]);

  const fetchEstimate = async () => {
    setIsLoading(true);
    try {
      const result = await estimateSalary(job, analysis);
      setData(result);
    } catch (error) {
      console.error("Failed to estimate salary", error);
    } finally {
      setIsLoading(false);
    }
  };

  if (!isOpen) return null;

  const formatCurrency = (amount: number, currency: string) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: currency,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-slate-950/90 backdrop-blur-sm" onClick={onClose}></div>
      
      <div className="relative w-full max-w-lg bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl overflow-hidden animate-fade-in-up">
        
        {/* Header */}
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-slate-900/50">
          <div>
            <h2 className="text-xl font-display font-bold text-white flex items-center gap-2">
              <DollarSign className="w-6 h-6 text-green-400" />
              Salary Estimator
            </h2>
            <p className="text-slate-400 text-sm">Market analysis for <span className="text-indigo-300 font-medium">{job.title}</span></p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-slate-800 rounded-full text-slate-400 hover:text-white transition-colors">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="p-8 bg-slate-950/30">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center h-48 space-y-4">
              <Loader2 className="w-10 h-10 text-green-500 animate-spin" />
              <div className="text-center">
                <p className="text-white font-medium">Analyzing market data...</p>
                <p className="text-slate-500 text-sm">Cross-referencing role, location, and experience.</p>
              </div>
            </div>
          ) : data ? (
            <div className="space-y-8">
              
              {/* Main Numbers */}
              <div className="text-center space-y-2">
                <p className="text-slate-400 text-sm uppercase tracking-wider font-medium">Estimated Annual Base</p>
                <div className="text-4xl md:text-5xl font-bold text-white tracking-tight">
                  {formatCurrency(data.min, data.currency)} <span className="text-slate-600 font-light">-</span> {formatCurrency(data.max, data.currency)}
                </div>
                <div className="flex items-center justify-center gap-2 mt-2">
                   <span className={`px-2 py-1 rounded text-xs font-bold uppercase border ${
                     data.confidence === 'High' ? 'bg-green-500/10 text-green-400 border-green-500/30' :
                     data.confidence === 'Medium' ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30' :
                     'bg-red-500/10 text-red-400 border-red-500/30'
                   }`}>
                     {data.confidence} Confidence
                   </span>
                </div>
              </div>

              {/* Visual Range Bar (Simplified) */}
              <div className="relative h-2 bg-slate-800 rounded-full overflow-hidden">
                <div className="absolute top-0 left-0 h-full bg-gradient-to-r from-green-600 to-emerald-400 w-full opacity-75"></div>
              </div>

              {/* Explanation */}
              <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50 flex gap-3">
                <Info className="w-5 h-5 text-indigo-400 flex-shrink-0 mt-0.5" />
                <p className="text-slate-300 text-sm leading-relaxed">
                  {data.explanation}
                </p>
              </div>

              <div className="text-center">
                 <p className="text-[10px] text-slate-500">
                   *Estimates are generated by AI based on aggregated market data and are for reference only.
                 </p>
              </div>

            </div>
          ) : (
            <div className="text-center text-slate-400">
              <p>Unable to retrieve salary data.</p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-800 bg-slate-900 flex justify-center">
          <button
            onClick={fetchEstimate}
            disabled={isLoading}
            className="flex items-center gap-2 px-4 py-2 text-slate-400 hover:text-white transition-colors text-sm font-medium"
          >
            <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin' : ''}`} />
            Refresh Estimate
          </button>
        </div>

      </div>
    </div>
  );
};

export default SalaryModal;
